#!/usr/bin/env bash

PN=$(cat ./pluginname)

docker plugin disable -f ${PN}
docker plugin rm -f ${PN}

service docker stop
service docker start

sudo cp -f ./container-launch.sh ./myplugin/rootfs/netapp/container-launch.sh
sudo cp -f ./trident ./myplugin/rootfs/netapp/trident
sudo cp -f ./plugin.json ./myplugin/config.json

sudo docker plugin create ${PN} ./myplugin 
./pushPlugin
sudo docker plugin rm $PN
sudo docker plugin install --disable --grant-all-permissions ${PN} debug=true 

