#!/bin/bash

CMD="rescan-scsi-bus.sh"
chroot /host /usr/bin/env -i PATH="/usr/bin:/sbin:/bin" which rescan-scsi-bus.sh >> /dev/null 2>&1
if [[ $? -ne 0 ]]; then
    chroot /host /usr/bin/env -i PATH="/usr/bin:/sbin:/bin" which rescan-scsi-bus >> /dev/null 2>&1
    if [[ $? -ne 0 ]]; then
        exit
    fi
    CMD="rescan-scsi-bus"
fi

chroot /host /usr/bin/env -i PATH="/usr/bin:/sbin:/bin" ${CMD} "${@:1}"
