version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - nakedret
  settings:
    gosec:
      excludes:
        - G402
        - G115
    govet:
      disable:
        - printf
    nakedret:
      max-func-lines: 60
    lll:
      line-length: 120
      tab-width: 4
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/netapp/trident
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
