kind: Pod
apiVersion: v1
metadata:
    name: etcdctl
spec:
  containers:
    - name: etcdctl
      image: kangarlou/network-utils
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /root/certs
          name: client-certs
      command: ["/bin/bash", "-c"]
      args: ["while true; do echo hello && sleep 60; done"]
  volumes:
    - name: client-certs
      secret:
        secretName: etcd-client-tls
