apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-anf-cloud-secret
type: Opaque
stringData:
  clientID: abcde356-bf8e-fake-c111-abcde35613aa
  clientSecret: rR0rUmWXfNioN1KhtHisiSAnoTherboGuskey6pU
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-anf-cloud
spec:
  version: 1
  storageDriverName: azure-netapp-files
  subscriptionID: 12abc678-4774-fake-a1b2-a7abcde39312
  tenantID: a7abcde3-edc1-fake-b111-a7abcde356cf
  location: usgovvirginia
  serviceLevel: Premium
  cloudConfiguration:
    cloudName: AzureGovernment
  credentials:
    name: backend-tbc-anf-cloud-secret
