apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-anf-cloud-custom-secret
type: Opaque
stringData:
  clientID: abcde356-bf8e-fake-c111-abcde35613aa
  clientSecret: rR0rUmWXfNioN1KhtHisiSAnoTherboGuskey6pU
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-anf-cloud-custom
spec:
  version: 1
  storageDriverName: azure-netapp-files
  subscriptionID: 12abc678-4774-fake-a1b2-a7abcde39312
  tenantID: a7abcde3-edc1-fake-b111-a7abcde356cf
  location: eastus
  serviceLevel: Premium
  cloudConfiguration:
    adAuthorityHost: https://login.microsoftonline.azurestack.contoso.com/
    audience: https://management.azurestack.contoso.com
    endpoint: https://management.azurestack.contoso.com
  credentials:
    name: backend-tbc-anf-cloud-custom-secret
