#!/usr/bin/env bash

rm -rf ./models
rm -rf ./client

# if you need to recreate the swagger_full_converted.yaml from the swagger_full.yaml, uncomment this
# ./preprocess.py

swagger generate client -f swagger_full_converted.yaml \
   -C ./templates/default-client.yml \
   --template-dir=./templates --allow-template-override  | tee regen.log

