apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-nas-virtual-pools-secret
type: Opaque
stringData:
  username: cluster-admin
  password: password
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-virtual-pools
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 10.0.0.1
  dataLIF: 10.0.0.2
  backendName: tbc-ontap-nas-virtual-pools
  svm: trident_svm
  credentials: 
    name: backend-tbc-ontap-nas-virtual-pools-secret
  defaults:
    spaceReserve: none
    encryption: 'false'
  labels:
    store: nas_economy_store
  region: us_east_1
  storage:
  - labels:
      app: msoffice
      cost: '100'
    zone: us_east_1a
    defaults:
      spaceReserve: volume
      encryption: 'true'
      unixPermissions: '0755'
  - labels:
      app: slack
      cost: '75'
    zone: us_east_1b
    defaults:
      spaceReserve: none
      encryption: 'true'
      unixPermissions: '0755'
  - labels:
      app: wordpress
      cost: '50'
    zone: us_east_1c
    defaults:
      spaceReserve: none
      encryption: 'true'
      unixPermissions: '0775'
  - labels:
      app: mysqldb
      cost: '25'
    zone: us_east_1d
    defaults:
      spaceReserve: volume
      encryption: 'false'
      unixPermissions: '0775'
