apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-nas-autoexport-secret
type: Opaque
stringData:
  username: cluster-admin
  password: password
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-autoexport
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 10.0.0.1
  dataLIF: 10.0.0.2
  backendName: tbc-ontap-nas-autoexport
  svm: trident_svm
  autoExportCIDRs:
  - 192.168.0.0/24
  # customExportClientIPs:
  # - 192.168.0.0/24
  autoExportPolicy: true
  # useRest: true
  credentials: 
    name: backend-tbc-ontap-nas-autoexport-secret
