// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStorageUnitAntiRansomwareSuspectGetParams creates a new StorageUnitAntiRansomwareSuspectGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStorageUnitAntiRansomwareSuspectGetParams() *StorageUnitAntiRansomwareSuspectGetParams {
	return &StorageUnitAntiRansomwareSuspectGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStorageUnitAntiRansomwareSuspectGetParamsWithTimeout creates a new StorageUnitAntiRansomwareSuspectGetParams object
// with the ability to set a timeout on a request.
func NewStorageUnitAntiRansomwareSuspectGetParamsWithTimeout(timeout time.Duration) *StorageUnitAntiRansomwareSuspectGetParams {
	return &StorageUnitAntiRansomwareSuspectGetParams{
		timeout: timeout,
	}
}

// NewStorageUnitAntiRansomwareSuspectGetParamsWithContext creates a new StorageUnitAntiRansomwareSuspectGetParams object
// with the ability to set a context for a request.
func NewStorageUnitAntiRansomwareSuspectGetParamsWithContext(ctx context.Context) *StorageUnitAntiRansomwareSuspectGetParams {
	return &StorageUnitAntiRansomwareSuspectGetParams{
		Context: ctx,
	}
}

// NewStorageUnitAntiRansomwareSuspectGetParamsWithHTTPClient creates a new StorageUnitAntiRansomwareSuspectGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewStorageUnitAntiRansomwareSuspectGetParamsWithHTTPClient(client *http.Client) *StorageUnitAntiRansomwareSuspectGetParams {
	return &StorageUnitAntiRansomwareSuspectGetParams{
		HTTPClient: client,
	}
}

/*
StorageUnitAntiRansomwareSuspectGetParams contains all the parameters to send to the API endpoint

	for the storage unit anti ransomware suspect get operation.

	Typically these are written to a http.Request.
*/
type StorageUnitAntiRansomwareSuspectGetParams struct {

	/* Fields.

	   Specify the fields to return.
	*/
	Fields []string

	/* StorageUnitUUID.

	   The UUID of the storage unit.

	   Format: uuid
	*/
	StorageUnitUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the storage unit anti ransomware suspect get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageUnitAntiRansomwareSuspectGetParams) WithDefaults() *StorageUnitAntiRansomwareSuspectGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the storage unit anti ransomware suspect get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StorageUnitAntiRansomwareSuspectGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) WithTimeout(timeout time.Duration) *StorageUnitAntiRansomwareSuspectGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) WithContext(ctx context.Context) *StorageUnitAntiRansomwareSuspectGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) WithHTTPClient(client *http.Client) *StorageUnitAntiRansomwareSuspectGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) WithFields(fields []string) *StorageUnitAntiRansomwareSuspectGetParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) SetFields(fields []string) {
	o.Fields = fields
}

// WithStorageUnitUUID adds the storageUnitUUID to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) WithStorageUnitUUID(storageUnitUUID strfmt.UUID) *StorageUnitAntiRansomwareSuspectGetParams {
	o.SetStorageUnitUUID(storageUnitUUID)
	return o
}

// SetStorageUnitUUID adds the storageUnitUuid to the storage unit anti ransomware suspect get params
func (o *StorageUnitAntiRansomwareSuspectGetParams) SetStorageUnitUUID(storageUnitUUID strfmt.UUID) {
	o.StorageUnitUUID = storageUnitUUID
}

// WriteToRequest writes these params to a swagger request
func (o *StorageUnitAntiRansomwareSuspectGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// binding items for fields
		joinedFields := o.bindParamFields(reg)

		// query array param fields
		if err := r.SetQueryParam("fields", joinedFields...); err != nil {
			return err
		}
	}

	// path param storage_unit.uuid
	if err := r.SetPathParam("storage_unit.uuid", o.StorageUnitUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamStorageUnitAntiRansomwareSuspectGet binds the parameter fields
func (o *StorageUnitAntiRansomwareSuspectGetParams) bindParamFields(formats strfmt.Registry) []string {
	fieldsIR := o.Fields

	var fieldsIC []string
	for _, fieldsIIR := range fieldsIR { // explode []string

		fieldsIIV := fieldsIIR // string as string
		fieldsIC = append(fieldsIC, fieldsIIV)
	}

	// items.CollectionFormat: "csv"
	fieldsIS := swag.JoinByFormat(fieldsIC, "csv")

	return fieldsIS
}
