// Code generated by go-swagger; DO NOT EDIT.

package ndmp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/netapp/trident/storage_drivers/ontap/api/rest/models"
)

// NewClusterNdmpModifyParams creates a new ClusterNdmpModifyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewClusterNdmpModifyParams() *ClusterNdmpModifyParams {
	return &ClusterNdmpModifyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewClusterNdmpModifyParamsWithTimeout creates a new ClusterNdmpModifyParams object
// with the ability to set a timeout on a request.
func NewClusterNdmpModifyParamsWithTimeout(timeout time.Duration) *ClusterNdmpModifyParams {
	return &ClusterNdmpModifyParams{
		timeout: timeout,
	}
}

// NewClusterNdmpModifyParamsWithContext creates a new ClusterNdmpModifyParams object
// with the ability to set a context for a request.
func NewClusterNdmpModifyParamsWithContext(ctx context.Context) *ClusterNdmpModifyParams {
	return &ClusterNdmpModifyParams{
		Context: ctx,
	}
}

// NewClusterNdmpModifyParamsWithHTTPClient creates a new ClusterNdmpModifyParams object
// with the ability to set a custom HTTPClient for a request.
func NewClusterNdmpModifyParamsWithHTTPClient(client *http.Client) *ClusterNdmpModifyParams {
	return &ClusterNdmpModifyParams{
		HTTPClient: client,
	}
}

/* ClusterNdmpModifyParams contains all the parameters to send to the API endpoint
   for the cluster ndmp modify operation.

   Typically these are written to a http.Request.
*/
type ClusterNdmpModifyParams struct {

	/* Info.

	   Information specification
	*/
	Info *models.ClusterNdmpProperties

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cluster ndmp modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterNdmpModifyParams) WithDefaults() *ClusterNdmpModifyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cluster ndmp modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterNdmpModifyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cluster ndmp modify params
func (o *ClusterNdmpModifyParams) WithTimeout(timeout time.Duration) *ClusterNdmpModifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cluster ndmp modify params
func (o *ClusterNdmpModifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cluster ndmp modify params
func (o *ClusterNdmpModifyParams) WithContext(ctx context.Context) *ClusterNdmpModifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cluster ndmp modify params
func (o *ClusterNdmpModifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cluster ndmp modify params
func (o *ClusterNdmpModifyParams) WithHTTPClient(client *http.Client) *ClusterNdmpModifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cluster ndmp modify params
func (o *ClusterNdmpModifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInfo adds the info to the cluster ndmp modify params
func (o *ClusterNdmpModifyParams) WithInfo(info *models.ClusterNdmpProperties) *ClusterNdmpModifyParams {
	o.SetInfo(info)
	return o
}

// SetInfo adds the info to the cluster ndmp modify params
func (o *ClusterNdmpModifyParams) SetInfo(info *models.ClusterNdmpProperties) {
	o.Info = info
}

// WriteToRequest writes these params to a swagger request
func (o *ClusterNdmpModifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Info != nil {
		if err := r.SetBodyParam(o.Info); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
